# Generated by Django 5.2.1 on 2025-06-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"], "verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="company",
            name="contact_person",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="company",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="company",
            name="register_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="company",
            name="vat_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
